/*
Code-string helpers for MKtl elements.

Reconstruct the elAt path of an element, generate action templates,
and list every action that fires for it.

Part of the ModalityContextMenu extension - these live on the element rather
than in the GUI because they are just as useful from the post window:

k = MKtl('grid', "intech-grid-nesso");
k.elAt(\knobModule, 3, 0).elemPath;			// -> [ knobModule, 3, 0 ]
k.elAt(\knobModule, 3, 0).elemPathString;	// -> "MKtl('grid').elAt(\knobModule, 3, 0)"
k.elAt(\knobModule, 3, 0).postElemInfo;
*/

+ MAbstractElement {

	// The path of keys / indices from mktl.elementGroup down to this element,
	// such that   source.elAt( *this.elemPath ) === this
	//
	// NOTE: MAbstractElement:keys looks like it does this, but it does not -
	// it recurses into MKtlElementGroup:keys, which returns a group's *child*
	// keys rather than its ancestor path. So we walk the parent chain here.
	elemPath {
		var path = [], node = this, group;
		while { (group = node.parent).notNil } {
			path = path.addFirst( node.prPathComponentIn( group ) );
			node = group;
		};
		^path
	}

	// "\knobModule, 3, 0"
	elemPathArgString {
		^this.elemPath.collect { |key| this.prCodeForKey(key) }.join(", ")
	}

	// "MKtl('grid').elAt(\knobModule, 3, 0)"
	elemPathString {
		var path = this.elemPath;
		var mktl = this.source;
		var mktlString = "MKtl(%)".format((mktl !? _.name ?? { '<mktl>' }).asCompileString);

		if (path.notEmpty) {
			^"%.elAt(%)".format(mktlString, this.elemPathArgString)
		};

		// no parent chain: either the root elementGroup itself, ...
		if (mktl.notNil and: { mktl.elementGroup === this }) {
			^"%.elementGroup".format(mktlString)
		};
		// ... or an element that was never attached to a group.
		// Fall back to the flat elementsDict key.
		^"%.dictAt(%)".format(mktlString, name.asCompileString)
	}

	// A bare skeleton in Modality's house style, ready to paste and fill in.
	// selector is \action_ (replaces) or \addAction (appends).
	actionTemplateString { |selector = \action_|
		var args = if (this.isKindOf(MKtlElementGroup)) { "|el, grp|" } { "|el|" };
		^"%.%({ %\n\t\n});".format(this.elemPathString, selector, args)
	}

	// for use in a SynthDef, via MAbstractElement:kr
	krCodeString {
		^"%.kr".format(this.elemPathString)
	}

	// Every action that fires when this element is moved, rendered as
	// re-evaluable code. doAction runs this element's own action, then every
	// ancestor via parent, then every group it was added to - so all three
	// are listed here.
	actionsAsString {
		^String.streamContents { |stream|
			var anyFound = false;

			stream << "/* ---------------------------------------------------------\n";
			stream << "   actions that fire for %\n".format(this.elemPathString);
			stream << "   %   type: %   ioType: %\n".format(name.asCompileString, type, ioType);
			stream << "   generated by ModalityContextMenu, %\n"
				.format(Date.localtime.stamp);
			stream << "--------------------------------------------------------- */\n\n";

			this.prActionOwners.do { |owner|
				var funcs = owner.prActionFuncs;
				if (funcs.notEmpty) {
					anyFound = true;
					if (owner === this) {
						stream << "// ---- own action ----\n";
					} {
						stream << "// ---- also fires, registered on % ----\n"
							.format(owner.elemPathString);
					};
					funcs.do { |func, i|
						stream << "%.%(\n%\n);\n\n".format(
							owner.elemPathString,
							if (i == 0) { "action_" } { "addAction" },
							func.asCompileString
						);
					};
				};
			};

			if (anyFound.not) {
				stream << "// no actions registered yet. Here is a template:\n\n";
				stream << this.actionTemplateString;
				stream << "\n";
			};
		}
	}

	postElemInfo {
		var funcs = this.prActionFuncs;
		"\n// ---------------- % ----------------\n".postf(this.elemPathString);
		"name:        %\n".postf(name.asCompileString);
		"class:       %\n".postf(this.class);
		"type:        %        ioType: %\n".postf(type, ioType);
		this.tryPerform(\deviceSpec) !? { |spec| "deviceSpec:  %\n".postf(spec) };
		"value:       %\n".postf(this.value);
		"deviceValue: %\n".postf(this.deviceValue);
		"actions:     % registered\n".postf(funcs.size);
		"enabled:     %\n".postf(enabled);
		"tags:        %\n".postf(tags);
		"elemDesc:\n".post;
		this.prPostDesc(elemDesc, "    ");
		"".postln;
		^this
	}

	//////////// private ////////////

	// Which key or index addresses this element inside the given group?
	// MKtlDesc:makeElemKeys fills missing keys with (i+1).asSymbol, so a key of
	// '4' at index 3 is positional noise - emit the integer index instead, which
	// is what reads naturally: elAt(\knobModule, 3, 0) rather than
	// elAt(\knobModule, '4', '1'). MKtlElementGroup:at resolves both forms.
	prPathComponentIn { |group|
		var key = group.elemKeyOf(this);
		var index = group.elemIndexOf(this);
		if (index.isNil) { ^key };
		if (key.isNil or: { key.asString == (index + 1).asString }) { ^index };
		^key
	}

	// Symbols that are valid identifiers read better as \name than as 'name',
	// which is how the Modality tutorials write them.
	prCodeForKey { |key|
		// NB matchRegexp takes the pattern as receiver: regexp.matchRegexp(string)
		if (key.isKindOf(Symbol)
			and: { "^[a-zA-Z_][a-zA-Z0-9_]*$".matchRegexp(key.asString) }) {
			^"\\" ++ key.asString
		};
		^key.asCompileString
	}

	// this element, plus every element whose action also fires for it
	prActionOwners {
		var owners = [];
		var visit;
		visit = { |el|
			if (el.notNil and: { owners.includes(el).not }) {
				owners = owners.add(el);
				visit.(el.parent);
				el.groups.do { |group| visit.(group) };
			};
		};
		visit.(this);
		^owners
	}

	prActionFuncs {
		var act = this.action;
		^case
			{ act.isNil }					{ [] }
			{ act.isKindOf(FunctionList) }	{ act.array.copy }
			{ true }						{ [act] }
	}

	// Walk the desc's parent chain, skipping levels that have nothing to show,
	// so the post does not fill up with empty "// inherited:" headers.
	// A group's desc holds its whole subtree under \elements, so drop that key.
	prPostDesc { |dict, indent = "    "|
		var levels = [], node = dict, keys;
		while { node.notNil } {
			keys = node.keys.asArray.select { |key| key != \elements }.sort;
			if (keys.notEmpty) { levels = levels.add([node, keys]) };
			node = node.tryPerform(\parent);
		};
		levels.do { |pair, i|
			if (i > 0) { "%// inherited:\n".postf(indent) };
			pair[1].do { |key| "%%: %\n".postf(indent, key, pair[0][key]) };
		};
		^this
	}
}
